backend:
  name: git-gateway
  branch: main

media_folder: "images" # uploads go here
public_folder: "/images"

collections:
    - name: "tuktuks"
    label: "Tuktuks"
    folder: "_tuktuks" # data will be saved here
    create: true
    slug: "{{fields.code}}"
    fields:
            - {label: "Title", name: "modelFull", widget: "string"}
            - {label: "Brand", name: "brand", widget: "select", options: ["Bajaj", "TVS", "Piaggio"]}
            - {label: "Model Type", name: "model", widget: "string", hint: "Duramax, Deluxe, Petrol, Diesel, RE 4S"}
            - {label: "Photo", name: "image", widget: "image"} # DRAG & DROP HERE
            - {label: "Area", name: "area", widget: "string"}
            - {label: "Year", name: "year", widget: "number"}
            - {label: "Mileage", name: "mileage", widget: "string"}
            - {label: "Price", name: "price", widget: "number"}
            - {label: "Code", name: "code", widget: "string"}