backend:
  name: github
  repo: tranzyman86-ux/Mombasa-tuktuks
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "static/images"
public_folder: "/images"

collections:
    - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Body", name: "body", widget: "markdown"}
